name: After merge
on:
  push:
    branches:
      - main
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.24.4'

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Run unit tests
        run: make test